# name: Run merger and save each hash

on:
    workflow_dispatch:


jobs:
  generate_hash_letters:
    runs-on: ubuntu-latest
    outputs:
        string_list: ${{ steps.generate.outputs.string_list }}
    steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.9'  # Specify your Python version
        - name: Install dependencies
          run: |
            pip install -e .

        - name: Generate Strings
          id: generate
          run: |
            # Run your script here to produce a list of strings
            message=$(python src/parselmouth/dump_producer.py)
            echo $message
            echo "string_list=$message" >> $GITHUB_OUTPUT
          env:
            R2_PREFIX_ACCOUNT_ID: ${{ secrets.R2_PREFIX_ACCOUNT_ID }}
            R2_PREFIX_ACCESS_KEY_ID: ${{ secrets.R2_PREFIX_ACCESS_KEY_ID }}
            R2_PREFIX_SECRET_ACCESS_KEY: ${{ secrets.R2_PREFIX_SECRET_ACCESS_KEY }}
            R2_PREFIX_BUCKET: ${{ secrets.R2_PREFIX_BUCKET }}


  dynamic_dump:
    runs-on: ubuntu-latest
    needs: generate_hash_letters
    strategy:
        matrix:
            subdirs: ${{fromJson(needs.generate_hash_letters.outputs.string_list)}}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run dumper
        env:
            R2_PREFIX_ACCOUNT_ID: ${{ secrets.R2_PREFIX_ACCOUNT_ID }}
            R2_PREFIX_ACCESS_KEY_ID: ${{ secrets.R2_PREFIX_ACCESS_KEY_ID }}
            R2_PREFIX_SECRET_ACCESS_KEY: ${{ secrets.R2_PREFIX_SECRET_ACCESS_KEY }}
            R2_PREFIX_BUCKET: ${{ secrets.R2_PREFIX_BUCKET }}
        run: python src/parselmouth/dump.py ${{ matrix.subdirs }}