# name: Run merger and save each hash

on:
    workflow_dispatch:
#   push:
#     branches:
#       - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run merger
        env:
            R2_ACCOUNT_ID: ${{ secrets.R2_ACCOUNT_ID }}
            R2_ACCESS_KEY_ID: ${{ secrets.R2_ACCESS_KEY_ID }}
            R2_SECRET_ACCESS_KEY: ${{ secrets.R2_SECRET_ACCESS_KEY }}
            R2_BUCKET: ${{ secrets.R2_BUCKET }}
        run: python src/parselmouth/merger.py