name: run pre-commit and type-checking

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up pixi
        uses: prefix-dev/setup-pixi@v0.8.1
        with:
          environments: >-
            lint
            type-checking

      - name: pre-commit
        run: pixi run pre-commit-run --color=always --show-diff-on-failure --all

      - name: type check
        run: pixi run type-check
