# name: Run tests for parselmouth

on:
    push:
    workflow_dispatch:
    pull_request:
  
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4

        - name: Set up Python
          uses: actions/setup-python@v5
          with:
            python-version: '3.9'  # Specify your Python version

        - uses: prefix-dev/setup-pixi@v0.5.1
          with:
            pixi-version: "latest"
            manifest-path: pyproject.toml

        - name: run tests
          run: | 
           pixi run run_tests
        